name: Cron-job-assingment

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      
  # Triggers the workflow every minute
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runner's shell
      - name: Run a one-line script
        run: echo "Usama Arhshad, Nazia Malik, Saadia Abdul jabbar, Raja Bilal"
